// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
#nullable disable

namespace SportNugget.Data.Models
{
    [Table("Test")]
    public partial class Test
    {
        [Key]
        [Column("PkId")]
        public int PkId { get; set; }
        [Column("TestName")]
        [StringLength(255)]
        public string TestName { get; set; }
    }
}
